#pragma once

#define VULKAN_MEMORY_ARENA 512 * 1024 * 1024
#define VULKAN_READBACK_MEMORY_ARENA 32 * 1024 * 1024

#define VULKAN_MAX_DEVICES 10u

#define VULKAN_MAX_COMMANDQUEUES 10u
#define VULKAN_MAX_COMMANDLISTS 64u

#define VULKAN_MAX_GRAPHICSHEAP 32
#define VULKAN_MAX_RESOURCES 1000000
#define VULKAN_MAX_SAMPLERS 2048
#define VULKAN_MAX_MIPS 16

#define VULKAN_MAX_SWAPCHAIN_BUFFERS 3
#define VULKAN_MAX_SWAPCHAINS 10u

#define VULKAN_MAX_LIBRARIES UINT16_MAX
#define VULKAN_MAX_PIPELINESTATES UINT16_MAX

