name: Build CI

on:
  push:

jobs:
  build_native:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/build-native.yml
    name: 'build-native-${{ matrix.platform }}-${{ matrix.architecture }}'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  build_dotnet:
    uses: ./.github/workflows/build-dotnet.yml
    secrets: inherit

  build_dotnet_native:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/build-dotnet-native.yml
    name: 'build-dotnet-native'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
    
  run_tests:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/run-tests.yml
    needs: [ build_native, build_dotnet, build_dotnet_native ]
    name: 'run-tests-${{ matrix.platform }}-${{ matrix.architecture }}'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
