name: Build Elemental Tools Native

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  build_tools_native_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Get Shader Compilers
      run: ./external/GetShaderCompilers.ps1

    - name: Build Windows Platform
      run: ./src/Elemental.Tools.Native/Build.ps1 -outputDirectory ./bin/ -configuration Release

    - name: Copy files Windows
      run: |
        cp ../../external/shader-compilers/dxc/bin/x64/*.dll ./bin/

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: ElementalToolsNative_windows_x64
        path: |
            ./src/Elemental.Tools.Native/bin/*.dll

  build_tools_native_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get Shader Compilers
      run: ./external/GetShaderCompilers.sh

    - name: Build MacOS Platform
      run: ./src/Elemental.Tools.Native/Build.sh -outputDirectory ./bin/ -configuration Release

    - name: Copy files MacOS
      run: |
        cp ../../external/shader-compilers/dxc/lib/*.dylib ./bin/

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: ElementalToolsNative_macos_x64
        path: |
            ./src/Elemental.Tools.Native/bin/*.dylib