name: Build CI

on:
  push:
  pull_request:

jobs:
  build_native:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/build-native.yml
    name: 'build-native'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  build_dotnet:
    uses: ./.github/workflows/build-dotnet.yml
    name: 'build-dotnet'
    secrets: inherit

  build_dotnet_native:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/build-dotnet-native.yml
    name: 'build-dotnet-native'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
    
  run_tests:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/run-tests.yml
    needs: [ build_native, build_dotnet, build_dotnet_native ]
    name: 'run-tests'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  ci-build-check:
    if: always() && github.event.pull_request
    runs-on: ubuntu-latest
    name: CI Build Check
    needs: [ run_tests ]
    uses: mheap/github-action-required-labels@master
    with:
      mode: exactly
      count: 0
      labels: build-fail
