on:
  workflow_call:
    inputs:
      version:
        description: "Version of the assembly (default: 1.0.0)"
        required: false
        type: string
        default: 1.0.0

jobs:
  build_dotnet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 8.0.100

    - name: Build Library
      run: |
        dotnet publish ./src/Elemental --disable-build-servers -p:BuildProjectReferences="False" -p:Version=${{ inputs.version }}
        dotnet publish ./src/Elemental.Tools --disable-build-servers -p:BuildProjectReferences="False" -p:Version=${{ inputs.version }}

    - name: Upload Binaries
      uses: actions/upload-artifact@master
      with:
        name: dotnet.bin
        path: ./artifacts/publish
