name: Build CI

on:
  push:
    branches: [ input-service ]

jobs:
  build_windows:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  build_dotnet:
    uses: ./.github/workflows/build-dotnet.yml
    secrets: inherit
    
  run_tests:
    uses: ./.github/workflows/run-tests.yml
    needs: [build_windows, build_dotnet]
    secrets: inherit
