on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ 
      (inputs.platform == 'osx' && 'macos-14') ||
      (inputs.platform == 'linux' && 'ubuntu-latest') ||
      (inputs.platform == 'win' && 'windows-latest')
      }}

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Setup Windows Dependencies
      if: inputs.platform == 'win'
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: ${{ inputs.architecture }}

    - name: Setup Linux Dependencies
      if: inputs.platform == 'linux'
      run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure Build
      run: cmake --preset release

    - name: Build
      run: cmake --build --preset release
          
    - name: Install
      run: cmake --install ./build-release --prefix ./install-release

    - name: Upload Elemental Binaries
      uses: actions/upload-artifact@master
      with:
        name: elemental.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./install-release/Elemental/

    - name: Upload Elemental Tools Binaries
      uses: actions/upload-artifact@master
      with:
        name: elemental-tools.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./install-release/ElementalTools/

    - name: Upload Tests Binaries
      uses: actions/upload-artifact@master
      with:
        name: tests.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./install-release/tests/

    - name: Upload Samples Binaries
      uses: actions/upload-artifact@master
      with:
        name: samples.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./install-release/samples/
