name: Build CI

on:
  push:
    branches: [ github-actions ]

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0, 17.5)'
        msbuild-architecture: x64

    - name: Build Windows Platform
      working-directory: ./src/Platforms/Windows
      run: ./Build.ps1 -outputDirectory ./bin/ -configuration Release
        
  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build MacOS Platform
      working-directory: ./src/Platforms/MacOS
      run: pwsh ./Build.ps1 -outputDirectory ./bin/ -configuration Release

  build_dotnet:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100

    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0, 17.5)'
        msbuild-architecture: x64

    - name: Build Library
      run: |
        dotnet build ./src/Elemental -c Release 
        
    - name: Build Samples
      run: |
        dotnet build ./samples/01-HelloWorld
        dotnet build ./samples/02-HelloWindow
        dotnet build ./samples/03-HelloTriangle


