name: Build CI

on:
  push:
  pull_request:

jobs:
  build_native:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/build-native.yml
    name: 'build-native'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  build_dotnet:
    uses: ./.github/workflows/build-dotnet.yml
    name: 'build-dotnet'
    secrets: inherit
    
  run_tests:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/run-tests.yml
    needs: [ build_native, build_dotneti ]
    name: 'run-tests'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  ci-build-check:
    if: always()
    runs-on: ubuntu-latest
    name: CI Build Check
    needs: [ run_tests ]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
