on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  build-dotnet-native:
    runs-on: ${{ 
      (inputs.platform == 'osx' && 'macos-13') ||
      (inputs.platform == 'linux' && 'ubuntu-latest') ||
      (inputs.platform == 'win' && 'windows-latest')
      }}

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 8.0.101

    - name: Build Tests
      run: |
        dotnet publish ./tests/Elemental.Tests.NativeApplicationTests --self-contained -r ${{ inputs.platform }}-${{ inputs.architecture }} -p:BuildNative="False"

    - name: Upload Binaries
      uses: actions/upload-artifact@master
      with:
        name: dotnet.tests.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./artifacts/publish
