name: Build CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/build.yml
    name: 'build'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
    
  run_tests:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/run-tests.yml
    needs: [ build ]
    name: 'run-tests'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  ci-build-check:
    if: always()
    runs-on: ubuntu-latest
    name: CI Build Check
    needs: [ run_tests ]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
