on:
  workflow_call:
    inputs:
      version:
        description: "Version of the assembly (default: 1.0.0)"
        required: false
        type: string
        default: 1.0.0

jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 8.0.101

    - name: Build Library
      run: |
        dotnet publish ./bindings/dotnet/src/Elemental -p:BuildNative="False" -p:Version=${{ inputs.version }} -v normal
        dotnet publish ./bindings/dotnet/src/Elemental.Tools -p:BuildNative="False" -p:Version=${{ inputs.version }}

    - name: Upload Binaries
      uses: actions/upload-artifact@master
      with:
        name: dotnet.bin
        path: ./bindings/dotnet/artifacts/publish
