name: Build CI

on:
  push:

jobs:
  build_native:
    strategy:
      matrix:
        platform: [win]
        architecture: [x64]
    uses: ./.github/workflows/build-native.yml
    name: 'build-native-${{ matrix.platform }}-${{ matrix.architecture }}'
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  build_dotnet:
    uses: ./.github/workflows/build-dotnet.yml
    secrets: inherit
    
  run_tests:
    uses: ./.github/workflows/run-tests.yml
    needs: [build_native, build_dotnet]
    secrets: inherit
