name: Build Dotnet

on:
  workflow_call:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: false
        type: string
        default: "1.0.0"
    secrets:
      NUGET_APIKEY:
        required: true

jobs:
  build_dotnet:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: SDK 8.0.100-rc.2.23502.2

    - name: Build Library
      run: |
        dotnet publish . -c Release -p:BuildProjectReferences="False" -p:Version=${{ inputs.tag }}

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: DotnetBinaries
        path: |
          ./.artifacts/
