name: Build Dotnet

on:
  workflow_call:
    inputs:
      version:
        description: "Version of the assembly (default: 1.0.0)"
        required: false
        type: string
        default: 1.0.0

jobs:
  build_dotnet:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100-rc.1.23455.8

    - name: .NET Restore
      run: dotnet restore
          
    - name: Build Library
      run: dotnet publish --no-restore -p:BuildProjectReferences="False" -p:Version=${{ inputs.version }}

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: dotnet.bin
        path: ./artifacts/publish
