name: Build CI

on:
  push:
    branches: [ input-service ]

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    name: 'build-windows'
    secrets: inherit

  build_dotnet:
    uses: ./.github/workflows/build-dotnet.yml
    name: 'build-dotnet'
    secrets: inherit
