name: Build CI

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/build.yml
    name: build
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  run_tests:
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/run-tests.yml
    needs: [build]
    name: run-tests
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  ci-build-check:
    if: always()
    runs-on: ubuntu-latest
    name: CI Build Check
    needs: [build, run_tests]
    steps:
      - name: Check build and test results
        if: >-
          ${{
               needs.build.result != 'success'
            || needs.run_tests.result != 'success'
          }}
        run: exit 1
