name: Build Windows

on:
  workflow_call:
    secrets:
      NUGET_APIKEY:
        required: true

jobs:
  build_windows_x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.0

    - name: Build Windows Platform
      run: |
        mkdir ./build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -G Ninja -B ./build -S . -DCMAKE_CXX_COMPILER=clang-cl
        cmake --build ./build --target Elemental.Native --config Release

    - name: Download Vulkan Loader
      working-directory: ./build/src/Elemental.Native/Windows
      run: |
        mkdir ./tmp/
        curl -L -o ./tmp/vulkan-loader.zip https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-runtime-components.zip

    - name: Extract Vulkan Loader
      working-directory: ./build/src/Elemental.Native/Windows
      run: |
        unzip ./tmp/vulkan-loader.zip -d ./bin/

    - name: Set Vulkan DLL Path
      id: set-vulkan-dll-path
      working-directory: ./build/src/Elemental.Native/Windows
      shell: bash
      run: |
        dllPath=$(find ./bin -name vulkan-1.dll -type f -print -quit)
        echo "vulkan_dll_path=$dllPath" >> $GITHUB_ENV

    - name: Copy files
      working-directory: ./build/src/Elemental.Native/Windows
      shell: bash
      run: |
        cp ${{ env.vulkan_dll_path }} .

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: native.bin.win-x64
        path: |
            ./build/src/Elemental.Native/Windows/*.dll

