name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
        type: string
      publish-nuget:
        description: "publish-nuget: true = publish nuget package. false = create the nuget package but don't publish it."
        required: true
        default: false
        type: boolean

jobs:
  release-elemental:
    uses: ./.github/workflows/release-elemental.yml
    name: 'release-elemental'
    with:
      tag: ${{ inputs.tag }}
      publish-nuget: ${{ inputs.publish-nuget }}