name: Release Elemental

on:
  workflow_call:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
        type: string
      publish-nuget:
        description: "publish-nuget: true = publish nuget package. false = create the nuget package but don't publish it."
        required: true
        default: false
        type: boolean

jobs:
  build_tools_windows_x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        
    - name: Get Shader Compilers
      working-directory: ./external
      shell: powershell
      run: ./GetShaderCompilers.ps1

    - name: Build Windows Platform
      working-directory: ./src/Elemental.Tools.Native
      run: ./Build.ps1 -outputDirectory ./bin/ -configuration Release

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: ElementalToolsNativex64
        path: |
            ./src/Elemental.Tools/bin/*.dll
        
  build_tools_dotnet:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.202

    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Build Library
      run: |
        dotnet build ./src/Elemental.Tools -c Release -p:CompileNative="False" -p:Version=${{ inputs.tag }} 

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: ElementalToolsDotnet

        path: |
          ./src/Elemental.Tools/bin/Release/net7.0/Elemental.Tools.dll
          ./src/Elemental.Tools/bin/Release/net7.0/Elemental.Tools.xml
          
  build_nuget:
    runs-on: windows-latest
    needs: [build_tools_windows_x64, build_tools_dotnet]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.202

    - name: Download Windows Native x64
      uses: actions/download-artifact@master
      with:
        name: ElementalToolsNativex64
        path: ./publish/Elemental.Tools/runtimes/win-x64
          
    - name: Download Dotnet Binaries
      uses: actions/download-artifact@master
      with:
        name: ElementalToolsDotnet
        path: ./publish/Elemental.Tools/lib/net7.0

    - name: Replace tokens in nuspec file
      uses: datamonsters/replace-action@master
      with:
        files: "./publish/Elemental.Tools/Elemental.Tools.nuspec"
        replacements: '#VERSION#=${{ inputs.tag }},#COMMIT#=${{ github.sha }}'

    - name: Nuget pack
      working-directory: ./publish/Elemental.Tools
      run: nuget.exe pack -OutputDirectory build

    # TODO: Create tag
    # TODO: Create Release

    - name: Push Nuget Package
      if: ${{ inputs.publish-nuget == true }}
      run: dotnet nuget push ./publish/Elemental.Tools/build/Elemental.Tools.${{ inputs.tag }}.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGET_APIKEY }}
          
    - name: Upload Nuget package
      uses: actions/upload-artifact@v3
      with:
        name: Elemental.${{ inputs.tag }}
        path: ./publish/Elemental.Tools/build/*.nupkg

    - name: Delete Windows Native x64
      uses: geekyeggo/delete-artifact@v2
      with:
          name: ElementalToolsNativex64

    - name: Delete Dotnet Binaries
      uses: geekyeggo/delete-artifact@v2
      with:
          name: ElementalToolsDotnet