on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  run_tests:
    runs-on: windows-latest

    steps:
    - name: Download Native Binaries ${{ inputs.platform }}-${{ inputs.architecture }}
      uses: actions/download-artifact@master
      with:
        name: native.bin.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./NativeApplicationTests/release/
          
    - name: Download Dotnet Binaries
      uses: actions/download-artifact@master
      with:
        name: dotnet.bin

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100-rc.1.23455.8

    - name: Run Tests
      run: dotnet test ./NativeApplicationTests/release/NativeApplicationTests.dll
