name: Run Tests

on:
  workflow_call:

jobs:
  run_tests:
    runs-on: windows-latest

    steps:
    - name: Download Windows Native x64
      uses: actions/download-artifact@master
      with:
        name: WindowsNativex64
          
    - name: Download Dotnet Binaries
      uses: actions/download-artifact@master
      with:
        name: DotnetBinaries


