on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  run_tests:
    runs-on: ${{ 
      ((inputs.platform == 'osx') && 'macos-14') ||
      (inputs.platform == 'linux' && 'ubuntu-latest') ||
      (inputs.platform == 'win' && 'windows-latest')
      }}

    steps:
    - name: Download Test Binaries
      uses: actions/download-artifact@master
      with:
        name: tests.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./

    - name: Extract Tests Archive (Windows)
      if: inputs.platform == 'win'
      run: 7z x ./tests.${{ inputs.platform }}-${{ inputs.architecture }}.zip -o"."

    - name: Extract Tests Archive
      if: inputs.platform != 'win'
      run: tar -xvf ./tests.${{ inputs.platform }}-${{ inputs.architecture }}.tar ./tests/

    - name: Run System Functions Tests
      if: inputs.platform != 'osx'
      run: ./Tests/SystemFunctionsTests/SystemFunctionsTests

    - name: Run System Functions Tests (MacOS)
      if: inputs.platform == 'osx'
      run: ./Tests/SystemFunctionsTests.app/Contents/MacOS/SystemFunctionsTests
    
    - name: Run Application Tests
      if: inputs.platform != 'osx'
      run: ./Tests/ApplicationTests/ApplicationTests

    - name: Run Application Tests (MacOS)
      if: inputs.platform == 'osx'
      run: ./Tests/ApplicationTests.app/Contents/MacOS/ApplicationTests
    
    - name: Run Tools Tests
      if: inputs.platform != 'osx'
      run: ./Tests/ToolsTests/ToolsTests

    - name: Run Tools Tests (MacOS)
      if: inputs.platform == 'osx'
      run: ./Tests/ToolsTests.app/Contents/MacOS/ToolsTests

      #- name: Run Graphics Tests
      #if: inputs.platform == 'win'
        #run: |
#$ErrorView = 'NormalView'
#        ./Tests/GraphicsTests
