on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  run_tests:
    runs-on: ${{ 
      ((inputs.platform == 'osx') && 'macos-14') ||
      (inputs.platform == 'linux' && 'ubuntu-latest') ||
      (inputs.platform == 'win' && 'windows-latest')
      }}

    steps:
    - name: Download Test Binaries
      uses: actions/download-artifact@master
      with:
        name: tests.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./Tests/

    - name: Run System Functions Tests
      run: ./Tests/SystemFunctionsTests
    
    - name: Run Application Tests
      run: ./Tests/ApplicationTests
    
        #run tools tests
      #- name: Run Graphics Tests
      #if: inputs.platform == 'win'
        #run: |
#$ErrorView = 'NormalView'
#        ./Tests/GraphicsTests
