on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  run_tests:
    runs-on: ${{ 
      ((inputs.platform == 'macos' && inputs.architecture == 'arm64') && 'macos-13-xlarge') ||
      ((inputs.platform == 'macos' && inputs.architecture != 'arm64') && 'macos-13') ||
      (inputs.platform == 'linux' && 'ubuntu-latest') ||
      (inputs.platform == 'windows' && 'windows-latest')
      }}

    steps:
    - name: Download Native Binaries ${{ inputs.platform }}-${{ inputs.architecture }}
      uses: actions/download-artifact@master
      with:
        name: native.bin.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./Tests/
 
    - name: Download Native Binaries
      if: inputs.platform != 'osx'
      uses: actions/download-artifact@master
      with:
        name: native.tests.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./Tests/

    - name: Download Dotnet Binaries
      uses: actions/download-artifact@master
      with:
        name: dotnet.tests.${{ inputs.platform }}-${{ inputs.architecture }}

    - name: Copy files
      run: cp -r ./Elemental.Tests.NativeApplicationTests/* ./Tests/

    - name: Copy MacOS native
      if: inputs.platform == 'osx'
      run: cp ./Tests/Elemental.Native.dylib ./Tests/Elemental.Tests.NativeApplicationTests.app/Contents/MacOS

    - name: Set Executable Permission
      if: inputs.platform == 'osx'
      run: |
        chmod +x ./Tests/Elemental.Tests.NativeSystemFunctionsTests
        chmod +x ./Tests/Elemental.Tests.NativeApplicationTests.app/Contents/MacOS/Elemental.Tests.NativeApplicationTests

    - name: Run Native System Functions Tests
      run: ./Tests/Elemental.Tests.NativeSystemFunctionsTests
    
    - name: Run NativeApplication Tests
      if: inputs.platform != 'osx'
      run: ./Tests/Elemental.Tests.NativeApplicationTests
    
    - name: Run NativeApplication Tests
      if: inputs.platform == 'osx'
      run: ./Tests/Elemental.Tests.NativeApplicationTests.app/Contents/MacOS/Elemental.Tests.NativeApplicationTests
