on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  run_tests:
    runs-on: ${{ 
      ((inputs.platform == 'osx') && 'macos-14') ||
      (inputs.platform == 'linux' && 'ubuntu-latest') ||
      (inputs.platform == 'win' && 'windows-latest')
      }}

    steps:
    - name: Download Native Binaries ${{ inputs.platform }}-${{ inputs.architecture }}
      uses: actions/download-artifact@master
      with:
        name: native.bin.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./Tests/
 
    - name: Download Native Test Binaries
      uses: actions/download-artifact@master
      with:
        name: native.tests.${{ inputs.platform }}-${{ inputs.architecture }}
        path: ./Tests/

    - name: Set Executable Permission
      if: inputs.platform == 'osx'
      run: |
        chmod +x ./Tests/SystemFunctionsTests
        chmod +x ./Tests/ApplicationTests
        chmod +x ./Tests/GraphicsTests

    - name: Run Native System Functions Tests
      run: ./Tests/SystemFunctionsTests
    
    - name: Run Application Tests
      run: ./Tests/ApplicationTests
    
    - name: Run Graphics Tests
      if: inputs.platform == 'win'
      shell: cmd
      run: ./Tests/GraphicsTests
